-- ============================================================
-- SkillMesh D1 种子数据
-- 20 条能力锚点
-- ============================================================

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('pdf-extract-text-001', 'PDF文本提取', 'PDF Text Extraction', '从PDF文件中提取全部文本内容，保留段落结构', 'Extract all text from PDF files while preserving paragraph structure', 'PDF文件URL或本地路径', 'PDF file URL or local path', '结构化文本字符串，包含页码映射', 'Structured text string with page number mapping', 'mcp://pymupdf-server/extract-text', 'mcp', 'data', 'https://github.com/pymupdf/PyMuPDF', 0.92, 1240, 0.25, 0.97, 0.10, 0.88, 1240, 0.24, '["保留段落结构","页码映射","多语言文本支持","批量处理"]', '["Preserve paragraphs","Page mapping","Multi-language","Batch processing"]', '将PDF文件URL或本地路径作为输入参数传入，返回包含页码映射的结构化文本。', 'Pass the PDF file URL or local path as input, returns structured text with page mapping.', '{"method":"tools/call","params":{"name":"extract-text","arguments":{"path":"/data/report.pdf"}}}', '2026-08-20', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('pdf-extract-table-002', 'PDF表格提取', 'PDF Table Extraction', '从PDF文件中提取结构化表格数据，支持多页多表', 'Extract structured table data from PDFs, supporting multi-page multi-table', 'PDF文件URL、页码范围（可选）', 'PDF file URL, page range (optional)', 'JSON格式表格数组，含行列结构', 'JSON array of tables with row/column structure', 'mcp://pdfplumber-server/extract-tables', 'mcp', 'data', 'https://github.com/jsvine/pdfplumber', 0.85, 890, 0.18, 0.94, 0.15, 0.82, 890, 0.25, '["多页多表提取","JSON结构化输出","行列自动识别","合并单元格处理"]', '["Multi-page/table","JSON output","Auto row/col detect","Merged cells"]', '通过MCP协议调用，指定PDF文件路径和页码范围，返回JSON格式的表格数组。', 'Invoke via MCP protocol, specify PDF path and page range, returns JSON table array.', '{"method":"tools/call","params":{"name":"extract-tables","arguments":{"path":"/data/report.pdf","pages":"1-5"}}}', '2026-08-12', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('web-scrape-003', '网页内容抓取', 'Web Content Scraper', '抓取任意网页的可见文本内容，自动去除广告和导航', 'Scrape visible text from any webpage, auto-removing ads and navigation', '目标网页URL', 'Target webpage URL', '纯文本内容、标题、元数据', 'Plain text content, title, metadata', 'mcp://crawlee-server/scrape', 'mcp', 'data', 'https://github.com/apify/crawlee', 0.78, 2100, 0.42, 0.91, 0.22, 0.75, 2100, 0.23, '["自动去广告","导航栏过滤","元数据提取","JavaScript渲染支持"]', '["Auto ad removal","Nav filtering","Metadata extraction","JS rendering"]', '通过MCP协议传入目标URL，自动抓取页面可见文本并去除广告和导航栏。', 'Send MCP call with target URL, auto-scrapes visible text removing ads and nav bars.', '{"method":"tools/call","params":{"name":"scrape","arguments":{"url":"https://example.com/article"}}}', '2026-08-05', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('image-ocr-004', '图片OCR识别', 'Image OCR Recognition', '识别图片中的印刷体和手写体文字，支持多语言', 'Recognize printed and handwritten text in images, multi-language support', '图片文件URL或Base64', 'Image file URL or Base64', '识别文本、置信度分数、坐标框', 'Recognized text, confidence scores, bounding boxes', 'mcp://tesseract-server/recognize', 'mcp', 'media', 'https://github.com/tesseract-ocr/tesseract', 0.88, 3400, 0.68, 0.96, 0.08, 0.90, 3400, 0.22, '["印刷体识别","手写体识别","多语言支持","坐标框输出"]', '["Print recognition","Handwriting","Multi-language","Bounding boxes"]', '通过MCP协议传入图片路径，自动识别图片中文字并返回文本、置信度和坐标框信息。', 'Pass image path via MCP, auto-recognizes text and returns text, confidence, and bounding boxes.', '{"method":"tools/call","params":{"name":"recognize","arguments":{"path":"/data/scan.png","lang":"chi_sim+eng"}}}', '2026-08-18', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('text-summarize-005', '文本摘要生成', 'Text Summarization', '对长文本生成提取式和生成式摘要，支持指定长度', 'Generate extractive and abstractive summaries for long text', '长文本字符串、期望摘要长度', 'Long text string, desired summary length', '摘要文本、关键句索引', 'Summary text, key sentence indices', 'prompt://summarize?max_length={n}', 'prompt', 'language', 'https://github.com/huggingface/transformers', 0.72, 5600, 0.90, 0.89, 0.05, 0.85, 5600, 0.21, '["提取式摘要","生成式摘要","长度可控","关键句索引"]', '["Extractive summary","Abstractive summary","Length control","Key sentence index"]', '通过Prompt协议传入长文本和期望长度，生成两种模式的摘要并标记关键句。', 'Pass long text and desired length via Prompt protocol, generates two-mode summaries with key sentences.', '{"prompt":"summarize","text":"Long article text here...","max_length":200}', '2026-08-22', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('code-explain-006', '代码解释与注释', 'Code Explanation', '为任意代码片段生成自然语言解释和行内注释', 'Generate natural language explanations and inline comments for code', '代码字符串、编程语言标识', 'Code string, programming language identifier', '解释文本、注释后的代码', 'Explanation text, commented code', 'mcp://tree-sitter-server/explain', 'mcp', 'ai', 'https://github.com/tree-sitter/tree-sitter', 0.81, 1800, 0.36, 0.93, 0.12, 0.79, 1800, 0.23, '["多语言支持","行内注释","逻辑解释","复杂度分析"]', '["Multi-language","Inline comments","Logic explanation","Complexity analysis"]', '通过MCP协议传入代码片段和语言标识，返回自然语言解释和注释后代码。', 'Pass code snippet and language via MCP, returns natural language explanation and commented code.', '{"method":"tools/call","params":{"name":"explain","arguments":{"code":"def fib(n): ...","lang":"python"}}}', '2026-07-30', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('csv-json-007', '数据格式转换', 'Data Format Converter', '在CSV、JSON、XML、YAML之间双向转换，保留数据类型', 'Bidirectional conversion between CSV, JSON, XML, YAML', '源数据字符串、源格式、目标格式', 'Source data string, source format, target format', '转换后的数据字符串', 'Converted data string', 'mcp://sqlite-utils/convert', 'mcp', 'data', 'https://github.com/simonw/sqlite-utils', 0.90, 4200, 0.84, 0.98, 0.03, 0.92, 4200, 0.22, '["CSV/JSON/XML/YAML","双向转换","类型保留","嵌套结构支持"]', '["CSV/JSON/XML/YAML","Bidirectional","Type preservation","Nested structures"]', '通过MCP协议传入源数据、源格式和目标格式，自动完成双向转换。', 'MCP call with source data, source format, and target format for auto bidirectional conversion.', '{"method":"tools/call","params":{"name":"convert","arguments":{"data":"...","from":"csv","to":"json"}}}', '2026-08-15', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('timezone-008', '时区转换', 'Timezone Converter', '将任意时间戳转换为目标时区，支持夏令时和历史时区', 'Convert any timestamp to target timezone with DST and historical support', '时间字符串、源时区、目标时区', 'Time string, source timezone, target timezone', '转换后的时间字符串、偏移量', 'Converted time string, offset', 'mcp://dateutil-server/convert', 'mcp', 'data', 'https://github.com/dateutil/dateutil', 0.95, 780, 0.16, 0.99, 0.02, 0.95, 780, 0.26, '["夏令时支持","历史时区","IANA时区库","偏移量输出"]', '["DST support","Historical zones","IANA database","Offset output"]', '通过MCP协议指定源时区和目标时区，自动处理夏令时和历史时区规则。', 'MCP call with source and target timezone, auto-handles DST and historical timezone rules.', '{"method":"tools/call","params":{"name":"convert","arguments":{"from":"America/New_York","to":"Asia/Shanghai","time":"2024-06-01 12:00"}}}', '2026-08-25', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('regex-gen-009', '正则表达式生成', 'Regex Generator', '根据自然语言描述生成匹配正则表达式，附带解释和测试用例', 'Generate matching regex from natural language description', '自然语言描述（如：匹配邮箱地址）', 'Natural language description', '正则表达式、解释、测试用例', 'Regex pattern, explanation, test cases', 'prompt://regex?desc={text}', 'prompt', 'ai', 'https://github.com/rust-lang/regex', 0.68, 3200, 0.64, 0.87, 0.06, 0.71, 3200, 0.22, '["自然语言输入","表达式解释","测试用例生成","多引擎兼容"]', '["Natural language input","Pattern explanation","Test case generation","Multi-engine"]', '通过Prompt协议传入自然语言描述，自动生成正则表达式、解释和测试用例。', 'Pass natural language description via Prompt protocol, auto-generates regex, explanation, and test cases.', '{"prompt":"regex","desc":"匹配中国大陆手机号码","engine":"javascript"}', '2026-07-28', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('doc-diff-010', '文档差异对比', 'Document Diff', '对比两份文本的差异，生成行级和字符级变更标记', 'Compare two texts and generate line-level and character-level diff', '原文本、修改后文本', 'Original text, modified text', '差异标记文本、变更统计', 'Diff-marked text, change statistics', 'mcp://difftastic-server/diff', 'mcp', 'data', 'https://github.com/Wilfred/difftastic', 0.86, 1500, 0.30, 0.95, 0.09, 0.84, 1500, 0.24, '["行级对比","字符级对比","变更统计","统一diff格式"]', '["Line-level diff","Char-level diff","Change stats","Unified diff format"]', '通过MCP协议传入原文本和修改后文本，生成行级和字符级差异标记。', 'Pass original and modified text via MCP, generates line-level and character-level diff.', '{"method":"tools/call","params":{"name":"diff","arguments":{"original":"Hello World","modified":"Hello SkillMesh"}}}', '2026-08-08', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('web-search-011', '联网搜索', 'Web Search', '执行互联网搜索，返回结构化结果含标题、摘要和URL', 'Execute internet search, returning structured results with title, snippet, and URL', '搜索关键词、结果数量（可选）', 'Search keywords, result count (optional)', '搜索结果列表，含标题、摘要、URL', 'Search result list with title, snippet, URL', 'mcp://searxng-server/search', 'mcp', 'ai', 'https://github.com/searxng/searxng', 0.76, 6800, 0.92, 0.90, 0.18, 0.87, 6800, 0.21, '["多引擎聚合","隐私保护","结构化结果","时间范围筛选"]', '["Multi-engine","Privacy","Structured results","Time range filter"]', '通过MCP协议传入搜索关键词，使用SearXNG多引擎聚合搜索，返回结构化结果。', 'Pass search keywords via MCP, uses SearXNG multi-engine meta-search, returns structured results.', '{"method":"tools/call","params":{"name":"search","arguments":{"q":"latest AI research 2026","count":10}}}', '2026-08-26', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('file-read-012', '文件读取', 'File Reader', '读取本地文件系统中任意文本文件，支持多种编码格式', 'Read any text file from local filesystem with multi-encoding support', '文件路径、编码格式（可选）', 'File path, encoding (optional)', '文件文本内容、行数、编码信息', 'File text content, line count, encoding info', 'mcp://filesystem-server/read', 'mcp', 'data', 'https://github.com/modelcontextprotocol/servers', 0.94, 9200, 0.95, 0.99, 0.04, 0.93, 9200, 0.20, '["多编码支持","大文件流式读取","行号输出","元数据提取"]', '["Multi-encoding","Streaming","Line numbers","Metadata"]', '通过MCP协议传入文件路径，自动检测编码并读取文本内容，返回带行号的内容。', 'Pass file path via MCP, auto-detects encoding and reads text content with line numbers.', '{"method":"tools/call","params":{"name":"read","arguments":{"path":"/project/src/main.py"}}}', '2026-08-24', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('db-query-013', '数据库查询', 'Database Query', '对SQLite数据库执行SQL查询，返回结构化结果集', 'Execute SQL queries against SQLite databases, return structured results', '数据库路径、SQL查询语句', 'Database path, SQL query string', '查询结果集（JSON数组）、列名、执行时间', 'Query result set (JSON array), column names, execution time', 'mcp://sqlite-server/query', 'mcp', 'data', 'https://github.com/sqlite/sqlite', 0.91, 4500, 0.88, 0.98, 0.06, 0.91, 4500, 0.21, '["SQLite支持","参数化查询","执行时间","列名输出"]', '["SQLite support","Parameterized","Timing","Column names"]', '通过MCP协议指定数据库路径和执行SQL查询，返回结构化结果集和列信息。', 'Specify database path and SQL query via MCP, returns structured result set and column info.', '{"method":"tools/call","params":{"name":"query","arguments":{"db":"/data/app.db","sql":"SELECT * FROM users WHERE active = 1"}}}', '2026-08-21', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('translate-014', '文本翻译', 'Text Translation', '在100+语言之间进行高质量文本翻译，保留格式', 'High-quality text translation between 100+ languages, preserving format', '源文本、源语言、目标语言', 'Source text, source language, target language', '翻译后文本、置信度分数', 'Translated text, confidence score', 'prompt://translate?from={lang}&to={lang}', 'prompt', 'language', 'https://github.com/argosopentech/argos-translate', 0.74, 7800, 0.94, 0.88, 0.07, 0.83, 7800, 0.20, '["100+语言","格式保留","置信度输出","批量翻译"]', '["100+ languages","Format preservation","Confidence score","Batch translation"]', '通过Prompt协议传入源文本和语言对，自动翻译并返回翻译结果和置信度。', 'Pass source text and language pair via Prompt, returns translation and confidence score.', '{"prompt":"translate","text":"Hello, how are you?","from":"en","to":"zh"}', '2026-08-19', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('sentiment-015', '情感分析', 'Sentiment Analysis', '分析文本的情感极性（正面/负面/中性）及强度分数', 'Analyze text sentiment polarity (positive/negative/neutral) with intensity', '待分析文本', 'Text to analyze', '情感标签、极性分数、情绪分布', 'Sentiment label, polarity score, emotion distribution', 'mcp://vader-server/analyze', 'mcp', 'ai', 'https://github.com/cjhutto/vaderSentiment', 0.82, 5600, 0.90, 0.92, 0.05, 0.86, 5600, 0.21, '["正/负/中性","强度分数","情绪分布","多语言"]', '["Pos/Neg/Neutral","Intensity","Emotion distribution","Multi-language"]', '通过MCP协议传入文本，使用VADER情感词典分析情感极性和强度分数。', 'Pass text via MCP, uses VADER sentiment lexicon to analyze polarity and intensity.', '{"method":"tools/call","params":{"name":"analyze","arguments":{"text":"This product is amazing! Highly recommended."}}}', '2026-08-10', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('ner-016', '命名实体识别', 'Named Entity Recognition', '从文本中识别并分类人名、地名、组织名等命名实体', 'Identify and classify named entities (persons, locations, organizations) from text', '待分析文本', 'Text to analyze', '实体列表，含类型、起始位置、置信度', 'Entity list with type, position, confidence', 'mcp://spacy-server/ner', 'mcp', 'ai', 'https://github.com/explosion/spaCy', 0.87, 4100, 0.82, 0.95, 0.08, 0.89, 4100, 0.22, '["人名/地名/组织","位置标注","置信度","多语言NER"]', '["Person/Loc/Org","Position tags","Confidence","Multi-language NER"]', '通过MCP协议传入文本，使用spaCy模型进行命名实体识别并返回分类实体列表。', 'Pass text via MCP, uses spaCy model for NER and returns classified entity list.', '{"method":"tools/call","params":{"name":"ner","arguments":{"text":"Apple Inc. was founded by Steve Jobs in Cupertino."}}}', '2026-08-16', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('image-gen-017', '图像生成', 'Image Generation', '根据文本描述生成图像，支持多种风格和尺寸', 'Generate images from text descriptions with multiple styles and sizes', '文本描述、风格、尺寸（可选）', 'Text description, style, size (optional)', '生成图像的URL或Base64数据', 'Generated image URL or Base64 data', 'mcp://stable-diffusion-server/generate', 'mcp', 'media', 'https://github.com/CompVis/stable-diffusion', 0.65, 8900, 0.96, 0.82, 0.25, 0.78, 8900, 0.20, '["文本到图像","多种风格","尺寸可控","批量生成"]', '["Text-to-image","Multiple styles","Size control","Batch generation"]', '通过MCP协议传入文本描述，使用Stable Diffusion生成对应图像。', 'Pass text description via MCP, uses Stable Diffusion to generate matching image.', '{"method":"tools/call","params":{"name":"generate","arguments":{"prompt":"A serene mountain lake at sunset","style":"photorealistic","size":"1024x768"}}}', '2026-08-23', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('email-send-018', '邮件发送', 'Email Sender', '通过SMTP或API发送邮件，支持HTML模板和附件', 'Send emails via SMTP or API with HTML templates and attachments', '收件人、主题、正文、附件（可选）', 'Recipient, subject, body, attachments (optional)', '发送状态、消息ID', 'Send status, message ID', 'mcp://resend-server/send', 'mcp', 'data', 'https://github.com/resend/resend-node', 0.83, 2600, 0.52, 0.96, 0.14, 0.88, 2600, 0.23, '["HTML模板","附件支持","批量发送","发送状态追踪"]', '["HTML templates","Attachments","Batch send","Status tracking"]', '通过MCP协议传入收件人、主题和正文，使用Resend发送邮件并返回状态。', 'Pass recipient, subject, and body via MCP, sends email via Resend and returns status.', '{"method":"tools/call","params":{"name":"send","arguments":{"to":"user@example.com","subject":"Hello","body":"<h1>Welcome</h1>"}}}', '2026-08-17', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('calendar-019', '日历事件创建', 'Calendar Event Creator', '创建和管理日历事件，支持iCal格式和重复规则', 'Create and manage calendar events with iCal format and recurrence rules', '事件标题、时间、地点、重复规则（可选）', 'Event title, time, location, recurrence (optional)', 'iCal事件对象、事件ID', 'iCal event object, event ID', 'mcp://icalendar-server/create', 'mcp', 'data', 'https://github.com/icalendar/icalendar', 0.79, 980, 0.20, 0.94, 0.11, 0.81, 980, 0.25, '["iCal标准","重复规则","多时区","提醒设置"]', '["iCal standard","Recurrence","Multi-timezone","Reminders"]', '通过MCP协议传入事件信息，生成标准iCal格式的日历事件。', 'Pass event info via MCP, generates standard iCal format calendar event.', '{"method":"tools/call","params":{"name":"create","arguments":{"title":"Team Meeting","start":"2026-09-01T10:00:00","end":"2026-09-01T11:00:00"}}}', '2026-08-02', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('sandbox-exec-020', '沙箱代码执行', 'Sandbox Code Execution', '在安全隔离沙箱中执行Python/JavaScript代码并返回结果', 'Execute Python/JavaScript code in secure isolated sandbox', '代码字符串、编程语言、超时时间（可选）', 'Code string, language, timeout (optional)', '标准输出、标准错误、执行时间、退出码', 'stdout, stderr, execution time, exit code', 'mcp://docker-sandbox/exec', 'mcp', 'dev', 'https://github.com/docker/docker-py', 0.70, 3100, 0.62, 0.85, 0.28, 0.73, 3100, 0.22, '["Python/JS支持","网络隔离","超时控制","资源限制"]', '["Python/JS support","Network isolation","Timeout control","Resource limits"]', '通过MCP协议传入代码和语言，在Docker沙箱中安全执行并返回输出。', 'Pass code and language via MCP, executes safely in Docker sandbox and returns output.', '{"method":"tools/call","params":{"name":"exec","arguments":{"code":"print(sum(range(1, 101)))","lang":"python","timeout":10}}}', '2026-07-25', 1);

INSERT INTO capabilities (id, name, name_en, "desc", desc_en, input, input_en, output, output_en, endpoint, endpoint_type, category, provenance, trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time, evidence_count, evidence_uncertainty, features, features_en, usage_guide, usage_guide_en, code_example, last_updated, version)
VALUES ('http-ip-geo-021', 'IP地理位置查询', 'IP Geolocation Lookup', '通过REST API查询任意IP地址的地理位置信息（国家、城市、ISP）', 'Query geolocation info (country, city, ISP) for any IP via REST API', 'IP地址（可选，默认为请求方IP）', 'IP address (optional, defaults to requester IP)', '国家、城市、ISP、经纬度、时区', 'Country, city, ISP, coordinates, timezone', 'https://ipapi.co/json/?ip={ip}', 'http', 'data', 'https://github.com/ipapi-co/ipapi', 0.94, 9500, 0.98, 0.98, 0.05, 0.95, 9500, 0.20, '["REST API","高可用","无需认证","速率限制友好"]', '["REST API","High availability","No auth required","Rate-limit friendly"]', '发送GET请求到 https://ipapi.co/json/ 即可获取当前IP的地理位置信息，支持自定义IP参数。', 'Send GET to https://ipapi.co/json/ to get geolocation info. Supports custom IP parameter.', '{"method":"GET","url":"https://ipapi.co/json/","headers":{"Accept":"application/json"}}', '2026-08-28', 1);