INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'pdf-merge-multiple-001',
  'PDF 合并',
  'PDF Merge',
  '合并多个 PDF 文件为一个 PDF 文件',
  'Merge multiple PDF files into a single PDF',
  '多个 PDF 文件路径或 URL',
  'Multiple PDF file paths or URLs',
  '合并后的 PDF 文件',
  'Merged PDF file',
  '/api/pdf/merge',
  'http',
  'document',
  'seed-import',
  0.6,
  0,
  0,
  0.5,
  0.3,
  0.8,
  0,
  0.5,
  '["批量合并","保持格式","支持加密PDF"]',
  '["Batch merge","Format preservation","Encrypted PDF support"]',
  '提供 PDF 文件列表，按顺序合并',
  'Provide a list of PDF files, merged in order',
  'curl -X POST /api/pdf/merge -F ''files=@a.pdf'' -F ''files=@b.pdf''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'pdf-rotate-pages-001',
  'PDF 页面旋转',
  'PDF Page Rotation',
  '旋转 PDF 中的指定页面',
  'Rotate specific pages in a PDF document',
  'PDF 文件 + 旋转角度（90/180/270）',
  'PDF file + rotation angle (90/180/270)',
  '旋转后的 PDF 文件',
  'Rotated PDF file',
  '/api/pdf/rotate',
  'http',
  'document',
  'seed-import',
  0.6,
  0,
  0,
  0.5,
  0.2,
  0.8,
  0,
  0.5,
  '["指定页面旋转","支持90/180/270度"]',
  '["Per-page rotation","90/180/270 degree support"]',
  '指定 PDF 文件和旋转角度',
  'Specify PDF file and rotation angle',
  'curl -X POST /api/pdf/rotate -F ''file=@doc.pdf'' -F ''angle=90'' -F ''pages=1,3,5''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'image-resize-batch-001',
  '图片批量缩放',
  'Batch Image Resize',
  '批量调整图片尺寸，支持多种输出格式',
  'Batch resize images with multiple output format support',
  '图片文件列表 + 目标尺寸',
  'Image file list + target dimensions',
  '缩放后的图片',
  'Resized images',
  '/api/image/resize',
  'http',
  'media',
  'seed-import',
  0.6,
  0,
  0,
  0.5,
  0.2,
  0.8,
  0,
  0.5,
  '["批量处理","保持比例","PNG/JPG/WebP输出"]',
  '["Batch processing","Aspect ratio preservation","PNG/JPG/WebP output"]',
  '上传图片并指定目标宽度/高度',
  'Upload images and specify target width/height',
  'curl -X POST /api/image/resize -F ''file=@photo.jpg'' -F ''width=800'' -F ''height=600''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'image-ocr-text-001',
  '图片 OCR 文字识别',
  'Image OCR Text Recognition',
  '从图片中提取文字内容，支持中英文',
  'Extract text from images, supporting Chinese and English',
  '图片文件',
  'Image file',
  '识别出的文字内容',
  'Recognized text content',
  '/api/image/ocr',
  'http',
  'ai',
  'seed-import',
  0.7,
  0,
  0,
  0.6,
  0.3,
  0.7,
  0,
  0.5,
  '["中英文识别","表格识别","手写体识别"]',
  '["Chinese/English recognition","Table recognition","Handwriting recognition"]',
  '上传图片文件，返回识别文字',
  'Upload image file, returns recognized text',
  'curl -X POST /api/image/ocr -F ''file=@scan.jpg'' -F ''lang=zh''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'text-summarize-zh-001',
  '中文文本摘要',
  'Chinese Text Summarization',
  '对中文长文本进行自动摘要生成',
  'Auto-generate summaries for long Chinese text',
  '中文文本内容',
  'Chinese text content',
  '摘要文本',
  'Summary text',
  '/api/text/summarize',
  'http',
  'ai',
  'seed-import',
  0.7,
  0,
  0,
  0.6,
  0.4,
  0.7,
  0,
  0.5,
  '["抽取式摘要","生成式摘要","长度可控"]',
  '["Extractive summary","Abstractive summary","Controllable length"]',
  '传入文本和期望摘要长度',
  'Pass text and desired summary length',
  'curl -X POST /api/text/summarize -d ''{"text":"长文本...","max_length":200}''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'text-translate-zh-en-001',
  '中英互译',
  'Chinese-English Translation',
  '中文与英文之间的双向翻译',
  'Bidirectional translation between Chinese and English',
  '待翻译文本 + 源语言/目标语言',
  'Source text + source/target language',
  '翻译结果',
  'Translation result',
  '/api/text/translate',
  'http',
  'ai',
  'seed-import',
  0.7,
  0,
  0,
  0.6,
  0.3,
  0.7,
  0,
  0.5,
  '["中→英","英→中","专业术语支持"]',
  '["Chinese→English","English→Chinese","Technical term support"]',
  '指定源语言和目标语言',
  'Specify source and target language',
  'curl -X POST /api/text/translate -d ''{"text":"你好","from":"zh","to":"en"}''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'audio-transcribe-speech-001',
  '语音转文字',
  'Speech to Text',
  '将音频文件中的语音转录为文字',
  'Transcribe speech from audio files to text',
  '音频文件（mp3/wav/m4a）',
  'Audio file (mp3/wav/m4a)',
  '转录文字',
  'Transcribed text',
  '/api/audio/transcribe',
  'http',
  'ai',
  'seed-import',
  0.7,
  0,
  0,
  0.6,
  0.3,
  0.6,
  0,
  0.5,
  '["多语言支持","说话人识别","时间戳标记"]',
  '["Multi-language","Speaker diarization","Timestamp markers"]',
  '上传音频文件，指定语言',
  'Upload audio file, specify language',
  'curl -X POST /api/audio/transcribe -F ''file=@recording.mp3'' -F ''lang=zh''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'video-extract-frames-001',
  '视频关键帧提取',
  'Video Keyframe Extraction',
  '从视频中提取关键帧图片',
  'Extract keyframe images from video',
  '视频文件 + 帧间隔',
  'Video file + frame interval',
  '关键帧图片列表',
  'Keyframe image list',
  '/api/video/extract-frames',
  'http',
  'media',
  'seed-import',
  0.6,
  0,
  0,
  0.5,
  0.2,
  0.6,
  0,
  0.5,
  '["场景检测","自定义间隔","缩略图生成"]',
  '["Scene detection","Custom interval","Thumbnail generation"]',
  '上传视频，设置帧间隔（秒）',
  'Upload video, set frame interval (seconds)',
  'curl -X POST /api/video/extract-frames -F ''file=@video.mp4'' -F ''interval=5''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'data-json-validate-001',
  'JSON Schema 校验',
  'JSON Schema Validation',
  '根据 JSON Schema 校验 JSON 数据格式',
  'Validate JSON data against a JSON Schema',
  'JSON 数据 + JSON Schema',
  'JSON data + JSON Schema',
  '校验结果和错误详情',
  'Validation result and error details',
  '/api/data/json-validate',
  'http',
  'developer',
  'seed-import',
  0.7,
  0,
  0,
  0.7,
  0.1,
  0.9,
  0,
  0.5,
  '["Draft 2020-12","详细错误定位","批量校验"]',
  '["Draft 2020-12","Detailed error location","Batch validation"]',
  '提供数据和 Schema 的 JSON',
  'Provide JSON data and schema',
  'curl -X POST /api/data/json-validate -d ''{"data":{},"schema":{}}''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);

INSERT OR IGNORE INTO capabilities (
  id, name, name_en, "desc", desc_en, input, input_en, output, output_en,
  endpoint, endpoint_type, category, provenance,
  trust_source, trust_usage, trust_usage_rate, trust_success, trust_risk, trust_time,
  evidence_count, evidence_uncertainty,
  features, features_en, usage_guide, usage_guide_en, code_example,
  contributor_login, contributor_id,
  last_updated, version
) VALUES (
  'data-csv-json-001',
  'CSV 转 JSON',
  'CSV to JSON Converter',
  '将 CSV 格式数据转换为 JSON 格式',
  'Convert CSV format data to JSON format',
  'CSV 文本或文件',
  'CSV text or file',
  'JSON 数组',
  'JSON array',
  '/api/data/csv-to-json',
  'http',
  'developer',
  'seed-import',
  0.7,
  0,
  0,
  0.7,
  0.1,
  0.9,
  0,
  0.5,
  '["自动类型推断","自定义分隔符","编码检测"]',
  '["Auto type inference","Custom delimiter","Encoding detection"]',
  '上传 CSV 文件或粘贴内容',
  'Upload CSV file or paste content',
  'curl -X POST /api/data/csv-to-json -F ''file=@data.csv''',
  'seed-importer',
  0,
  '2026-09-05',
  1
);